In [1]:
import numpy as np
import pandas as pd

actions_p1 = ["戦略1", "戦略2"]
actions_p2 = ["戦略1", "戦略2"]

# 自分で利得を設定する
U1 = np.array([
    [3, 0],
    [4, 1]
])

U2 = np.array([
    [3, 4],
    [0, 1]
])

df_U1 = pd.DataFrame(U1, index=actions_p1, columns=actions_p2)
df_U2 = pd.DataFrame(U2, index=actions_p1, columns=actions_p2)

print("プレイヤー1の利得行列 U1")
display(df_U1)

print("プレイヤー2の利得行列 U2")
display(df_U2)

プレイヤー1の利得行列 U1

     戦略1  戦略2
戦略1    3    0
戦略2    4    1

プレイヤー2の利得行列 U2

     戦略1  戦略2
戦略1    3    4
戦略2    0    1